name: Echoing

on:
  push:

jobs:
  test_local:
    name: Test local
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Local Hi
        run: echo "Hi from local"

  test_remote:
    permissions:
      id-token: write # need this for OIDC
      contents: read
    uses: Iv-viZone/templates/.github/workflows/terraforming.yml@main
