name: Terraforming

on:
  push:

jobs:
  test:
    permissions:
      id-token: write # need this for OIDC
      contents: read
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Local Hi
        run: echo "Hi from local"

      - name: Remote Hi
        uses: Iv-viZone/templates/.github/workflows/terraforming.yml@main